tupla = ("azul", "amarelo", "lilás", "preto", "branco", "rosa", "marrom", "verde", "roxo", "vermelho")
print(tupla[0:2])
print(tupla[2:4])
print(tupla[4:6])
print(tupla[6:8])
print(tupla[8:10])
print(tupla[:])
